apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: TimescaleDB
    access: proxy
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASS}
    jsonData:
      database: ${DB_NAME}
      sslmode: "disable"
      timescaledb: true
      postgresVersion: 1500
    isDefault: true
    editable: false


